name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Lean ツールチェーンをインストール (elan経由)
      - name: Install elan (Lean toolchain manager)
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Check versions
        run: |
          lean --version
          lake --version

      - name: Get mathlib cache
        run: lake exe cache get

      - name: Build project
        run: lake build
